version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: predictions
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # optional external exposure

  yolo:
    image: ${YOLO_IMAGE:-adhamsaif16/yolo5tech:0.0.1}
    pull_policy: always
    environment:
      - DB_BACKEND=postgres
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=predictions
    depends_on:
      - postgres
    ports:
      - "${YOLO_PORT:-8080}:8080"
    volumes:
      - ./uploads:/app/uploads
      - ~/.aws:/root/.aws:ro

  ollama-ui:
    image: ${OLLAMA_UI_IMAGE:-adhamsaif16/ollama-ui:0.0.1}
    pull_policy: always
    environment:
      - YOLO_SERVICE=${YOLO_SERVICE:-http://yolo:8080}
      - AWS_SDK_LOAD_CONFIG=1
      - AWS_REGION=eu-west-1
      - AWS_S3_BUCKET=adhamsaif16
    ports:
      - "${OLLAMA_UI_PORT:-3000}:3000"
    depends_on:
      - yolo
    volumes:
      - ~/.aws:/root/.aws:ro

volumes:
  pgdata:
