version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: predictions
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  yolo:
    image: adhamsaif16/yolo5tech:0.0.1
    environment:
      - DB_BACKEND=postgres
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=predictions
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ~/.aws:/root/.aws:ro


  ollama-ui:
    image: adhamsaif16/ollama-ui:0.0.1
    environment:
      - YOLO_SERVICE=yolo:8080
      - AWS_SDK_LOAD_CONFIG=1
      - AWS_REGION=eu-west-1
      - AWS_S3_BUCKET=adhamsaif16
  
    ports:
      - "3000:3000"

    depends_on:
      - yolo
    volumes:
      - ~/.aws:/root/.aws:ro

volumes:
  pgdata: